# Generated by Django 5.0.7 on 2024-08-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('summary', models.TextField(blank=True)),
                ('type_of_book', models.CharField(max_length=50)),
                ('readers', models.CharField(blank=True, max_length=250)),
                ('price', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
                ('genres', models.ManyToManyField(to='books.genres')),
            ],
        ),
    ]
