# Generated by Django 5.0.7 on 2024-08-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['name']},
        ),
        migrations.AddIndex(
            model_name='books',
            index=models.Index(fields=['name'], name='books_books_name_bb734e_idx'),
        ),
    ]
